# -*- coding: utf-8 -*-
"""Python_Assignment. ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Q8WLOGcmWvnXR8sjWgXqfe_i0zTy4Wn

🔹 Level 1: Prime Number Checker

-This program checks whether a given number is a prime number.
"""

def is_prime(number):
    """
    Function to check if a number is prime.
    A prime number is only divisible by 1 and itself.
    """
    if number <= 1:
        return False

    for i in range(2, int(number ** 0.5) + 1):
        if number % i == 0:
            return False

    return True


# Test Level 1
num = int(input("Enter a number to check if it's prime: "))
if is_prime(num):
    print(f"{num} is a Prime Number.")
else:
    print(f"{num} is NOT a Prime Number.")

"""Level 2: Vowel Counter


Counts the number of vowels in a string.
"""

def count_vowels(text):
    """
    Function to count vowels in a string.
    Vowels: a, e, i, o, u (both lowercase and uppercase)
    """
    vowels = "aeiouAEIOU"
    count = 0

    for char in text:
        if char in vowels:
            count += 1

    return count

string_input = input("\nEnter a string: ")
print(f"Number of vowels: {count_vowels(string_input)}")

"""Level 3: CLI Calculator

A simple Command Line Calculator that performs basic arithmetic operations.
"""

def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    if b == 0:
        return "Error! Division by zero."
    return a / b


def calculator():
    """
    CLI-based calculator program.
    """
    print("\n--- Simple Calculator ---")
    print("1. Add")
    print("2. Subtract")
    print("3. Multiply")
    print("4. Divide")

    choice = input("Choose an operation (1/2/3/4): ")

    if choice in ['1', '2', '3', '4']:
        num1 = float(input("Enter first number: "))
        num2 = float(input("Enter second number: "))

        if choice == '1':
            print("Result:", add(num1, num2))
        elif choice == '2':
            print("Result:", subtract(num1, num2))
        elif choice == '3':
            print("Result:", multiply(num1, num2))
        elif choice == '4':
            print("Result:", divide(num1, num2))
    else:
        print("Invalid input!")


# Run calculator
calculator()